pull_request_rules:
  - name: Automatic merge
    description: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success = `cargo check/test/build` on ubuntu-latest
      - check-success = `cargo check/test/build` on macos-latest
      - check-success = cargo-deny (advisories)
      - check-success = cargo-deny (bans licenses sources)
      - check-success = codecov-check
    actions:
      merge:
        method: squash
